Models/Administracao.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ITicket.Models {
    public class Administracao {
       
    }
}

Controllers/AdministracaoController.cs
using Microsoft.AspNetCore.Mvc;
using ITicket.Models; 


public class AdministracaoController : Controller
{
    private readonly ContextoDb _contexto;

    public AdministracaoController(ContextoDb context)
    {
        _contexto = context;
    }


    //metodo para cadastrar usuario
    //method to register new user
    [HttpPost]
    public IActionResult Create(Usuario usuario)
    {
        if (ModelState.IsValid)
        {
            _contexto.Add(usuario);
            _contexto.SaveChanges();

            ViewBag.Message = "Usuario Cadastrado com Sucesso!";

            return View("~/Views/Home/Administracao.cshtml", usuario);
        }

        return View("~/Views/Home/Administracao.cshtml", usuario);
    }

}

Controllers/ChamadoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ITicket.Models;
using System.ComponentModel;


public class ChamadoController : Controller
{
    private readonly ContextoDb _contexto;
    private readonly IEmailService _emailService;

    public ChamadoController(ContextoDb context, IEmailService emailService)
    {
        _contexto = context;
        _emailService = emailService;
    }


    //metodo para buscar prioridade por descrição / method to search priority by description
    [HttpGet]
    public IActionResult GetPriorityForDescription(string descricao)
    {
        var servico = _contexto.Servico.FirstOrDefault(s => s.Descricao == descricao);
        if (servico != null)
        {
            return Ok(servico.Prioridade);
        }
        else
        {
            return NotFound();
        }
    }

     //metodo popular campos Nome, Departamento, Cargo e Email / method to populate fields Name, Department, Position and Email 
    [HttpGet]
    public IActionResult AbrirChamado()
    {
        var loggedInUsername = HttpContext.Session.GetString("Username");
        var user = _contexto.Usuario.FirstOrDefault(u => u.Username == loggedInUsername);
        var servicos = _contexto.Servico.Select(s => s.Descricao).ToList();
        var email = user.Email;

        var viewModel = new ChamadoUsuarioViewModel
        {
            Usuario = new Usuario
            {
                Nome = user.Nome,
                Departamento = user.Departamento,
                Cargo = user.Cargo,
                Email = user.Email,
            },
            Servico = servicos // adiciona os valores de Descricao ao view / adds the values of Descricao to the view
        };

        return View("~/Views/Home/AbrirChamado.cshtml", viewModel);
    }

    //metodo para abrir chamado / method to open a ticket
    [HttpPost]
    public async Task<IActionResult> AbrirChamado(Chamado chamado)
    {
        if (ModelState.IsValid)
        {
            chamado.Abertura = DateTime.Now;
            chamado.Status = "Novo";
            if (chamado.Servico != null)
            {
                var servico = _contexto.Servico.FirstOrDefault(s => s.Descricao == chamado.Servico.Descricao);

                if (servico != null)
                {
                    chamado.Servico = servico;
                    chamado.DescricaoServico = servico.Descricao;

                    if (servico.IdServico == null) // verifica se servico é null / checks if servico is null
                    {
                        ModelState.AddModelError("", "Service Id is null.");
                        return View("~/Views/Home/Error.cshtml");
                    }

                    bool isMassivo = false;
                    bool.TryParse(chamado.Massivo, out isMassivo);
                    if (isMassivo)
                    {
                        chamado.Prioridade = servico.Prioridade == "Baixa" ? "Media" : "Alta";
                    }
                    else
                    {
                        chamado.Prioridade = servico.Prioridade;
                    }

                    // calculo SLA / SLA calculation
                    switch (chamado.Prioridade)
                    {
                        case "Alta":
                            chamado.HoraLimite = chamado.Abertura.GetValueOrDefault().AddHours(isMassivo ? 1 : 1);
                            break;
                        case "Media":
                            chamado.HoraLimite = chamado.Abertura.GetValueOrDefault().AddHours(isMassivo ? 2 : 24);
                            break;
                        case "Baixa":
                        default:
                            if (!isMassivo)
                            {
                                chamado.HoraLimite = chamado.Abertura.GetValueOrDefault().AddDays(5);
                            }
                            break;
                    }
                }
                else
                {
                    ModelState.AddModelError("", "No matching service found.");
                    return View("~/Views/Home/Error.cshtml");
                }
            }
            else
            {
                ModelState.AddModelError("", "Service is null.");
                return View("~/Views/Home/Error.cshtml");
            }

            System.Diagnostics.Debug.WriteLine($"Prioridade: {chamado.Prioridade}");
            _contexto.Add(chamado);
            _contexto.SaveChanges();

            var username = HttpContext.Session.GetString("Username");
            var usuario = _contexto.Usuario.FirstOrDefault(u => u.Username == username);

            if (usuario != null)
            {
                await _emailService.SendEmailAsync(usuario.Email, "iticket.lab@gmail.com", chamado.Titulo, chamado.Descricao);
            }
            else
            {
                ModelState.AddModelError("", "The user does not exist.");
                return View("~/Views/Home/Error.cshtml");
            }

            TempData["Message"] = "Chamado Aberto com Sucesso!";

            var viewModel = new ChamadoUsuarioViewModel
            {
                Chamado = chamado,
                Usuario = usuario,
                Servico = _contexto.Servico.Select(s => s.Descricao).ToList() // busca todas as descricoes de serviço do banco
            };

            return View("~/Views/Home/AbrirChamado.cshtml", viewModel);
        }
        else
        {
            ModelState.AddModelError(string.Empty, "Nao foi possivel abrir o chamado.");

            var username = HttpContext.Session.GetString("Username");
            var usuario = _contexto.Usuario.FirstOrDefault(u => u.Username == username);

            var viewModel = new ChamadoUsuarioViewModel
            {
                Chamado = chamado,
                Usuario = usuario,
                Servico = _contexto.Servico.Select(s => s.Descricao).ToList() // busca todas as descricoes de serviço do banco
            };

            return View("~/Views/Home/AbrirChamado.cshtml", viewModel);
        }
    }
}

Controllers/HomeController.cs
using ITicket.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using SQLitePCL;
using System.Linq;
using System.Security.Claims;

namespace ITicket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ContextoDb _contexto;

        public HomeController(ContextoDb contexto)
        {
            _contexto = contexto;
        }

        public IActionResult MinhaConta()
        {
            // resgata o nome do usuario da sessao atual
            var username = HttpContext.Session.GetString("Username");

            // procura o usuario no db
            var usuario = _contexto.Usuario.FirstOrDefault(u => u.Username == username);

            // caso nao seja encontrado, redireciona para pag de login
            if (usuario == null)
            {
                return RedirectToAction("Login", "Account");
            }

            // passa o usuario para a view
            return View(usuario);
        }

        //exibe os chamados abertos de todos os usuarios e controla o filtro de buscas / displays all open tickets from all users and controls search filters
        public IActionResult Index(int page = 1, string sort = null, string filtro = null, string valor = null)
        {
            var username = HttpContext.Session.GetString("Username");
            if (username == null)
            {
                return View("Login");
            }

            int pageSize = 10;
            var chamados = _contexto.ChamadoView.AsQueryable();
            ViewBag.Filtro = filtro;
            ViewBag.Valor = valor;

            if (filtro == "Todos")
            {
                chamados = chamados.Where(c => c.Abertura >= DateTime.Now.AddDays(-365));
            }
            else if (!string.IsNullOrEmpty(filtro) && !string.IsNullOrEmpty(valor))
            {
                switch (filtro)
                {
                    case "IdChamado":
                        if (int.TryParse(valor, out int idChamado))
                        {
                            chamados = chamados.Where(c => c.IdChamado == idChamado);
                        }
                        
                        else
                        {
                            return BadRequest("Numero de chamado invalido");
                        }
                        break;
                    case "Abertura":
                        if (DateTime.TryParse(valor, out DateTime abertura))
                        {
                            chamados = chamados.Where(c => c.Abertura.HasValue && c.Abertura.Value.Date == abertura.Date);
                        }
                        
                        else
                        {
                            return BadRequest("Data de abertura invalida");
                        }
                        break;
                    case "Solicitante":
                        chamados = chamados.Where(c => c.Solicitante.ToLower().Contains(valor.ToLower()));
                        break;
                    case "Status":
                        chamados = chamados.Where(c => c.Status.ToLower().Contains(valor.ToLower()));
                        break;
                    case "HoraLimite":
                        if (DateTime.TryParse(valor, out DateTime horaLimite))
                        {
                            chamados = chamados.Where(c => c.HoraLimite.HasValue && c.HoraLimite.Value.Date == horaLimite.Date);
                        }
                        
                        else
                        {
                            return BadRequest("formato de SLA invalido");
                        }
                        break;
                }
            }

            // realiza o sort toda vez que a coluna e clicada / sorts every time a column is clicked
            if (!string.IsNullOrEmpty(sort))
            {
                switch (sort)
                {
                    case "IdChamado":
                        chamados = chamados.OrderBy(c => c.IdChamado);
                        break;
                    case "Abertura":
                        chamados = chamados.OrderBy(c => c.Abertura);
                        break;
                    case "Solicitante":
                        chamados = chamados.OrderBy(c => c.Solicitante);
                        break;
                    case "Status":
                        chamados = chamados.OrderBy(c => c.Status);
                        break;
                    case "HoraLimite":
                        chamados = chamados.OrderBy(c => c.HoraLimite);
                        break;
                }
            }

            return View(chamados.ToList());
        }

        //devolve a tela Adm / returns Adm screen
        public IActionResult Administracao()
        {
            return View();
        }

        //devolve a tela MeusChamados / returns MeusChamados screen
        public IActionResult MeusChamados()
        {
            var username = HttpContext.Session.GetString("Username");
            var userNome = _contexto.Usuario.FirstOrDefault(u => u.Username == username)?.Nome;
            var chamado = _contexto.MeuChamadoPreview.Where(p => p.Solicitante == userNome).ToList();
            return View(chamado);

        }

        //exibe detalhes do chamado quando clicado / displays ticket details when clicked
        [HttpGet]
        public IActionResult Details(int id)
        {
            var chamado = _contexto.MeuChamadoView.FirstOrDefault(c => c.IdChamado == id);
            if (chamado == null)
            {
                return NotFound();
            }

            return Json(chamado);
        }

        //devolve a pagina de login / returns login page
        public IActionResult Login()
        {

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Administracao.cshtml
@{
    ViewData["Title"] = "Administração";
}
<h1>@ViewData["Title"]</h1>


@{
    if (!String.IsNullOrEmpty(ViewBag.Message))
    {
        <div class="alert alert-success">
            @ViewBag.Message
        </div>
    }
}


@model ITicket.Models.Usuario
<form asp-action="Create" asp-controller="Administracao" method="post">
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <label for="Nome">Nome:</label>
            <input type="text" class="form-control mb-3" asp-for="Nome">

            <label for="Email">Email:</label>
            <input type="email" class="form-control mb-3" asp-for="Email">
        </div>
        <div class="col-md-6">
            <label for="Departamento">Departamento:</label>
            <input type="text" class="form-control mb-3" asp-for="Departamento">

            <label for="Cargo">Cargo:</label>
            <input type="text" class="form-control mb-3" asp-for="Cargo">
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <label for="Telefone">Telefone:</label>
            <input type="text" class="form-control mb-3" asp-for="Telefone">
        </div>
        <div class="col-md-4">
            <label for="Ramal">Ramal:</label>
            <input type="text" class="form-control mb-3" asp-for="Ramal">
        </div>
        <div class="col-md-4">
            <label for="Gestor">Gestor:</label>
            <input type="text" class="form-control mb-3" asp-for="Gestor">
        </div>
        <div class="col-md-6">
            <label for="Usuario">Usuário:</label>
            <input type="text" class="form-control mb-3" asp-for="Username">
            <label for="Senha">Senha:</label>
            <input type="password" class="form-control mb-3" asp-for="Senha">
        </div>
    </div>

    <div class="row">
        
        <div class="col-md-6">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="IsSolicitante">
                <label class="form-check-label" for="Solicitante">
                    Solicitante
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="IsAtendente">
                <label class="form-check-label" for="Atendente">
                    Atendente
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="IsAdm">
                <label class="form-check-label" for="Adm">
                    Adm
                </label>
            </div>
        </div>
    </div>   

    <div class="row">
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </div>
</div>
</form>
<br></br>
<hr>
<br></br>

<div class="container mt-6">
    <div class="row">
        <div class="col-md-3">
            <label for="Id">ID:</label>
            <input type="text" class="form-control" id="Id" name="Id">
        </div>
        <div class="col-md-3">
            <label for="NomeBuscar">Nome:</label>
            <input type="text" class="form-control" id="NomeBuscar" name="NomeBuscar">
        </div>
        <div class="col-md-3">
            <label for="EmailBuscar">Email:</label>
            <input type="email" class="form-control" id="EmailBuscar" name="EmailBuscar">
        </div>
        <div class="col-md-3">
            <button type="submit" class="btn btn-primary mt-4">Buscar</button>
        </div>
    </div>
    
    <div class="row mt-4">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Username</th>
                        <th>Senha</th>
                        <th>E-mail</th>
                        <th>Solicitante</th>
                        <th>Atendente</th>
                        <th>Adm</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Criar a task para popular os campos da tebal -->
                    <!-- Cada linha deve ter um botão "Editar" -->
                    <tr>
                        <td>Nome1</td>
                        <td>Username1</td>
                        <td>********</td>
                        <td>email1@example.com</td>
                        <td><input type="checkbox" disabled checked></td>
                        <td><input type="checkbox" disabled checked></td>
                        <td><input type="checkbox" disabled checked></td>
                        <td><button class="btn btn-primary">Editar</button></td>
                    </tr>
                    <tr>
                        <td>Nome2</td>
                        <td>Username2</td>
                        <td>********</td>
                        <td>email2@example.com</td>
                        <td><input type="checkbox" disabled></td>
                        <td><input type="checkbox" disabled checked></td>
                        <td><input type="checkbox" disabled></td>
                        <td><button class="btn btn-primary">Editar</button></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model List<ITicket.Models.ChamadoView>

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Seu Título</title>

    <!-- CSS do Bootstrap 4 (via CDN) -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Biblioteca de ícones do Bootstrap (via CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    
    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 

    <!-- JavaScript do Bootstrap 4 (via CDN, necessário para alguns recursos do Bootstrap) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-3">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Home" asp-action="MinhaConta">Minha Conta</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="Administracao">Administração</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="MeusChamados">Meus Chamados</a>
                        </div>
                    </li>
                </ul>
                <a class="btn btn-primary" asp-action="AbrirChamado" asp-controller="Chamado">
                    Abrir Chamado
                </a>
            </div>
        </div>
    </nav>

   

    <script>
        $(document).ready(function() {
            if (sessionStorage.getItem("isAuthenticated") !== "true") {
                $('#loginModal').modal('show');
            }
        });
    </script>

    
<script>
    $(document).ready(function() {
        if (sessionStorage.getItem("isAuthenticated") !== "true") {
            $('#loginModal').modal('show');
        }
    });
</script>



    <div class="text-center">
        <h2>Consultar Chamado</h2>
        <br>
        <br>
        <form>
          <div class="input-group">
            <select id="filtro" class="form-control">
                <option value="IdChamado">Todos</option>
                <option value="IdChamado">Nr. Chamado</option>
                <option value="Abertura">Data de Abertura</option>
                <option value="Solicitante">Criado Por</option>
                <option value="Status">Status</option>
                <option value="HoraLimite">SLA</option>
            </select>
            <input type="text" class="form-control" id="texto-exemplo" placeholder="Enter search value">
            <input type="text" class="form-control d-none" id="data-inicio" placeholder="Data de Início">
            <input type="text" class="form-control d-none" id="data-fim" placeholder="Data de Fim">
            <button id="filtrar-button" class="btn btn-primary">Filtrar</button>
        </div>
        
        </form>

        <div class="container mt-5">
            <div class="text-center">
                <h2>Histórico de Chamados</h2>
            </div>
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th scope="col"><a href="@Url.Action("Index", new { sort = "IdChamado" })">NR.CHAMADO</a></th>
                        <th scope="col"><a href="@Url.Action("Index", new { sort = "Abertura" })">DATA DE ABERTURA</a></th>
                        <th scope="col"><a href="@Url.Action("Index", new { sort = "Solicitante" })">CRIADO POR</a></th>
                        <th scope="col"><a href="@Url.Action("Index", new { sort = "Status" })">STATUS</a></th>
                        <th scope="col"><a href="@Url.Action("Index", new { sort = "HoraLimite" })">SLA</a></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var chamado in Model) {
                        <tr>
                            <td>@chamado.IdChamado</td>
                            <td>@chamado.Abertura</td>
                            <td>@chamado.Solicitante</td>
                            <td>@chamado.Status</td>
                            <td>@chamado.HoraLimite</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
       <div class="pagination">
            <a href="@Url.Action("Index", new { page = 1, filtro = ViewBag.Filtro, valor = ViewBag.Valor })">First</a>
            <a href="@Url.Action("Index", new { page = ViewBag.Page - 1, filtro = ViewBag.Filtro, valor = ViewBag.Valor })">Previous</a>
            <a href="@Url.Action("Index", new { page = ViewBag.Page + 1, filtro = ViewBag.Filtro, valor = ViewBag.Valor })">Next</a>
        </div>


    </div>








   

    

    <!-- Seu script de inicialização do datepicker -->
    <script>
        var urlAction = '@Url.Action("Index")';

        $(document).ready(function() {
            $('#filtro').on('change', function() {
                var selectedOption = $(this).val();

                if (selectedOption === 'Abertura' || selectedOption === 'HoraLimite') {
                    $('#texto-exemplo').addClass('d-none');
                    $('#data-inicio, #data-fim').removeClass('d-none').datepicker();
                } else {
                    $('#texto-exemplo').removeClass('d-none');
                    $('#data-inicio, #data-fim').addClass('d-none');
                }
            });

            $('#filtrar-button').on('click', function(e) {
                e.preventDefault();

                var selectedOption = $('#filtro').val();
                var inputValue = selectedOption === 'Abertura' || selectedOption === 'HoraLimite' ? $('#data-inicio').val() + ' - ' + $('#data-fim').val() : $('#texto-exemplo').val();

                window.location.href = urlAction + '?filtro=' + selectedOption + '&valor=' + inputValue;
            });
        });
    </script> 
    
    

    
    <script>

        
           $(document).ready(function() {
                $('#filtrar-button').on('click', function(e) {
                    e.preventDefault(); // Prevent the form from submitting

                    var selectedOption = $('#filtro').val(); // Get the selected option from the dropdown
                    var inputValue = $('#texto-exemplo').val(); // Get the input value

                    // Redirect to the Index action with the selected option and input value as parameters
                    window.location.href = '@Url.Action("Index")?filtro=' + selectedOption + '&valor=' + inputValue;
                });
            });

    

    <script>  
        $(document).ready(function () {
            $('#loginForm').submit(function (event) {
                event.preventDefault(); // Impede o envio padrão do formulário

                $.ajax({
                    url: $(this).attr('action'), // Obtém o URL de destino do formulário
                    method: $(this).attr('method'), // Obtém o método do formulário (POST neste caso)
                    data: $(this).serialize(), // Obtém os dados do formulário
                    success: function (response) {
                        console.log(response);
                        // Lida com a resposta do servidor
                        if (response.ok) {
                            localStorage.setItem("isAuthenticated", "true");
                            $('#loginModal').modal('hide');
                            window.location.href = '/Home/Index';
                        } else {
                            alert('Credenciais inválidas. Tente novamente.');
                        }
                    },
                    error: function () {
                        alert('Ocorreu um erro ao processar a solicitação. Tente novamente mais tarde.');
                    }
                });
            });
        });
    </script>
        

</body>
</html>

Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="d-flex justify-content-center align-items-center vh-100">
    <form asp-controller="Account" asp-action="ValidateLogin" method="post" class="w-50">
        <h2 class="form-group text-center">Login</h2>
        <div class="form-group">
            <label for="Username">Usuario:</label>
            <input type="text" class="form-control" id="Username" name="Username">
        </div>
        <div class="form-group">
            <label for="Password">Senha:</label>
            <input type="password" class="form-control mb-3" id="Password" name="Senha">
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
        <div class="form-group text-center">
            <a href="#" class="text-decoration-none">Esqueceu sua senha?</a>
        </div>
    </form>
</div>